#!/usr/bin/env bash
# Configures nginx server to redirect request.

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/tosmel2 permanent;" /etc/nginx/sites-enabled/default
