#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo touch /usr/share/nginx/html/error404.html
sudo chmod 777 /usr/share/nginx/html/error404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error404.html
sudo sed -i '/server_name _;/a error_page 404 /error404.html;\nlocation = /error404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
