#!/usr/bin/env bash
#more sigtrap handling exercises
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
echo $$ > /var/run/myscript.pid
while true; do
    echo To infinity and beyond
    sleep 2
done
