#!/usr/bin/env bash
#output some information about a file
file="bestschool"
if [ -e $file ]; then
    echo $file file exists
    if [ -s $file ]; then
	echo $file file is not empty
    else
	echo $file file is empty
    fi
    if ! [ -d $file ]; then
	echo $file is a regular file
    fi
else
    echo $file file does not exist
fi
